[2025-07-25T18:23:38.658+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-25T18:23:39.986+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.load_songplays_fact_table scheduled__2025-07-25T10:00:00+00:00 [queued]>
[2025-07-25T18:23:40.313+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.load_songplays_fact_table scheduled__2025-07-25T10:00:00+00:00 [queued]>
[2025-07-25T18:23:40.314+0700] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2025-07-25T18:23:41.548+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_songplays_fact_table> on 2025-07-25 10:00:00+00:00
[2025-07-25T18:23:41.566+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_local_postgres_pipeline', 'load_songplays_fact_table', 'scheduled__2025-07-25T10:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_pjt.py', '--cfg-path', '/tmp/tmpsotc8o30']
[2025-07-25T18:23:41.571+0700] {logging_mixin.py:188} WARNING - /home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=18516) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-25T18:23:41.572+0700] {standard_task_runner.py:91} INFO - Job 64: Subtask load_songplays_fact_table
[2025-07-25T18:23:41.573+0700] {standard_task_runner.py:63} INFO - Started process 18520 to run task
[2025-07-25T18:23:48.030+0700] {task_command.py:426} INFO - Running <TaskInstance: etl_local_postgres_pipeline.load_songplays_fact_table scheduled__2025-07-25T10:00:00+00:00 [running]> on host DESKTOP-9M5T9P5.localdomain
[2025-07-25T18:23:52.922+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='phuongnt226' AIRFLOW_CTX_DAG_ID='etl_local_postgres_pipeline' AIRFLOW_CTX_TASK_ID='load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-25T10:00:00+00:00'
[2025-07-25T18:23:52.924+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-25T18:23:52.946+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-25T18:23:52.947+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 164, in <lambda>
    python_callable=lambda: load_table(sql_queries.songplay_table_insert),
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'helpers.sql_queries' has no attribute 'songplay_table_insert'
[2025-07-25T18:23:53.625+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_local_postgres_pipeline, task_id=load_songplays_fact_table, run_id=scheduled__2025-07-25T10:00:00+00:00, execution_date=20250725T100000, start_date=20250725T112339, end_date=20250725T112353
[2025-07-25T18:23:53.913+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 64 for task load_songplays_fact_table (module 'helpers.sql_queries' has no attribute 'songplay_table_insert'; 18520)
[2025-07-25T18:23:53.925+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-25T18:23:54.736+0700] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-25T18:23:54.785+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
