[2025-07-26T00:00:12.703+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-26T00:00:13.839+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.stage_songs scheduled__2025-07-25T17:00:00+00:00 [queued]>
[2025-07-26T00:00:14.022+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.stage_songs scheduled__2025-07-25T17:00:00+00:00 [queued]>
[2025-07-26T00:00:14.023+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2025-07-26T00:00:14.210+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): stage_songs> on 2025-07-25 17:00:00+00:00
[2025-07-26T00:00:14.223+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_local_postgres_pipeline', 'stage_songs', 'scheduled__2025-07-25T17:00:00+00:00', '--job-id', '203', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_pjt.py', '--cfg-path', '/tmp/tmpj4hu34dl']
[2025-07-26T00:00:14.225+0700] {logging_mixin.py:188} WARNING - /home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1697) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T00:00:14.225+0700] {standard_task_runner.py:91} INFO - Job 203: Subtask stage_songs
[2025-07-26T00:00:14.225+0700] {standard_task_runner.py:63} INFO - Started process 1706 to run task
[2025-07-26T00:00:16.668+0700] {task_command.py:426} INFO - Running <TaskInstance: etl_local_postgres_pipeline.stage_songs scheduled__2025-07-25T17:00:00+00:00 [running]> on host DESKTOP-9M5T9P5.localdomain
[2025-07-26T00:00:22.646+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='phuongnt226' AIRFLOW_CTX_DAG_ID='etl_local_postgres_pipeline' AIRFLOW_CTX_TASK_ID='stage_songs' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-25T17:00:00+00:00'
[2025-07-26T00:00:22.648+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-26T00:00:23.398+0700] {base.py:84} INFO - Using connection ID 'postgres_id' for task execution.
[2025-07-26T00:00:23.997+0700] {logging_mixin.py:188} INFO - Found 71 song files.
[2025-07-26T00:00:24.105+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-26T00:00:24.106+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 38, in stage_songs_to_postgres
    cur.execute("SELECT 1 FROM staging_log WHERE file_path = %s", (file_path,))
psycopg2.errors.UndefinedTable: relation "staging_log" does not exist
LINE 1: SELECT 1 FROM staging_log WHERE file_path = '/home/ngtph/air...
                      ^

[2025-07-26T00:00:24.880+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_local_postgres_pipeline, task_id=stage_songs, run_id=scheduled__2025-07-25T17:00:00+00:00, execution_date=20250725T170000, start_date=20250725T170013, end_date=20250725T170024
[2025-07-26T00:00:25.251+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 203 for task stage_songs (relation "staging_log" does not exist
LINE 1: SELECT 1 FROM staging_log WHERE file_path = '/home/ngtph/air...
                      ^
; 1706)
[2025-07-26T00:00:25.282+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-26T00:00:27.024+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
