[2025-07-26T08:17:08.561+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-26T08:17:09.400+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.load_song_dim_table scheduled__2025-07-26T01:00:00+00:00 [queued]>
[2025-07-26T08:17:09.622+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_postgres_pipeline.load_song_dim_table scheduled__2025-07-26T01:00:00+00:00 [queued]>
[2025-07-26T08:17:09.622+0700] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2025-07-26T08:17:09.917+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_song_dim_table> on 2025-07-26 01:00:00+00:00
[2025-07-26T08:17:09.928+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_local_postgres_pipeline', 'load_song_dim_table', 'scheduled__2025-07-26T01:00:00+00:00', '--job-id', '409', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_pjt.py', '--cfg-path', '/tmp/tmpl96iq69v']
[2025-07-26T08:17:09.930+0700] {standard_task_runner.py:91} INFO - Job 409: Subtask load_song_dim_table
[2025-07-26T08:17:09.931+0700] {logging_mixin.py:188} WARNING - /home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5662) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T08:17:09.932+0700] {standard_task_runner.py:63} INFO - Started process 5667 to run task
[2025-07-26T08:17:12.826+0700] {task_command.py:426} INFO - Running <TaskInstance: etl_local_postgres_pipeline.load_song_dim_table scheduled__2025-07-26T01:00:00+00:00 [running]> on host DESKTOP-9M5T9P5.localdomain
[2025-07-26T08:17:18.606+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='phuongnt226' AIRFLOW_CTX_DAG_ID='etl_local_postgres_pipeline' AIRFLOW_CTX_TASK_ID='load_song_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-26T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-26T01:00:00+00:00'
[2025-07-26T08:17:18.607+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-26T08:17:19.443+0700] {base.py:84} INFO - Using connection ID 'postgres_id' for task execution.
[2025-07-26T08:17:20.114+0700] {sql.py:470} INFO - Running statement: 
    INSERT INTO songs (songid, title, artistid, year, duration)
    SELECT DISTINCT song_id, title, artist_id, year, duration
    FROM staging_songs
, parameters: None
[2025-07-26T08:17:20.232+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-26T08:17:20.233+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 100, in load_songs_table
    execute_sql(sql_queries.SqlQueries.song_table_insert)
  File "/home/ngtph/airflow/dags/etl_pipeline_pjt.py", line 17, in execute_sql
    result = hook.run(sql_statement)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 418, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/ngtph/airflow/airflow_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 475, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "songs_pkey"
DETAIL:  Key (songid)=(SOZVMJI12AB01808AF) already exists.

[2025-07-26T08:17:21.034+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_local_postgres_pipeline, task_id=load_song_dim_table, run_id=scheduled__2025-07-26T01:00:00+00:00, execution_date=20250726T010000, start_date=20250726T011709, end_date=20250726T011721
[2025-07-26T08:17:21.286+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 409 for task load_song_dim_table (duplicate key value violates unique constraint "songs_pkey"
DETAIL:  Key (songid)=(SOZVMJI12AB01808AF) already exists.
; 5667)
[2025-07-26T08:17:21.316+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-26T08:17:23.207+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
